version: '2'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: ${PROJECT}_prometheus
        volumes:
            - ./.docker/prometheus/config:/etc/prometheus/
            - ./.docker/prometheus/data:/prometheus
        command:
            --config.file=/etc/prometheus/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/etc/prometheus/console_libraries
            --web.console.templates=/etc/prometheus/consoles
            --storage.tsdb.retention=200h
            --web.enable-lifecycle
        expose:
            - 9090
        ports:
            - ${DOCKER}:9090:9090
        links:
            - blackbox-exporter
        networks:
            - ${PROJECT}_net

    grafana:
        image: grafana/grafana:latest
        container_name: ${PROJECT}_grafana
        volumes:
            - ./.docker/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - GF_USERS_ALLOW_SIGN_UP=false
        links:
            - prometheus
        ports:
            - ${DOCKER}:3000:3000
        networks:
            - ${PROJECT}_net

    blackbox-exporter:
        image: prom/blackbox-exporter:latest
        container_name: ${PROJECT}_blackbox
        volumes:
            - ./.docker/blackbox/config:/blackbox
        command: --config.file=/blackbox/blackbox.yml
        networks:
            - ${PROJECT}_net

    alertmanager:
        image: prom/alertmanager:latest
        container_name: ${PROJECT}_alertmanager
        ports:
            - 9093:9093
        volumes:
            - ./.docker/alertmanager/:/etc/alertmanager/
        command:
            --config.file=/etc/alertmanager/config/config.yml
            --storage.path=/alertmanager
        networks:
            - ${PROJECT}_net

networks:
    monitoring_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK}